server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api   #添加路由的前缀
  routes:
    item-service: /item/**
  ignored-patterns: /upload/**
  ignored-services:
    - upload-service # 忽略upload-service服务



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillseconds: 5000 #熔断超时时长5000ms

ribbon:
  ConnectTimeout: 1000 # ribbon链接超时时长
  ReadTimeout: 3500 # ribbon读取超时时长
  MaxAutoRetries: 0 # 当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切断服务重试次数